name: Deploy to Staging

on:
  push:
    branches: [develop] # or "master" or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/adminarachnova/arachnova-x-me19-be/
            git fetch origin develop
            git reset --hard origin/develop
            npm ci 
            npm run build
            pm2 restart me19-be-staging || pm2 start "node dist/index.js" --name "me19-be-staging"
